# Project related configuration
smanga:
  # Name
  name: Smart Manga Business
  # Version
  version: 4.5.1
  # Copyright year
  copyrightYear: 2020
  # Example demo switch
  demoEnabled: true
  # File path example (Windows configuration D:/smanga/uploadPath, Linux configuration /home/smanga/uploadPath)
  profile: D:/smanga/uploadPath
  # Get ip address switch
  addressEnabled: false

# Development environment configuration
server:
  # The HTTP port of the server, the default is 80
  port: 6061
  servlet:
    # Application access path
    context-path: /
  tomcat:
    # URI encoding of tomcat
    uri-encoding: UTF-8
    # Tomcat maximum number of threads, the default is 200
    max-threads: 800
    # The number of threads that Tomcat starts to initialize, the default value is 25
    min-spare-threads: 30
 
# Log configuration
logging:
  level:
    com.smanga: debug
    org.springframework: warn

# User configuration
user:
  password:
    # Wrong password {maxRetryCount} locked for 10 minutes
    maxRetryCount: 5

# Spring configuration
spring:
  # Template engine
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # Disable caching
    cache: false
  # Resource information
  messages:
    # Internationalized resource file path
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: dev
  # File Upload
  servlet:
     multipart:
       # Single file size
       max-file-size:  10MB
       # Set the total uploaded file size
       max-request-size:  20MB
  # Service module
  devtools:
    restart:
      # Hot deployment switch
      enabled: true

# MyBatis
mybatis:
    # Search for specified package alias
    typeAliasesPackage: com.smanga.**.domain
    # Configure mapper scanning and find all mapper.xml mapping files
    mapperLocations: classpath*:mapper/**/*Mapper.xml
    # Load the global configuration file
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper paging plugin
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # Login address
    loginUrl: /index
    # 权Restrict authentication failure addresses
    unauthorizedUrl: /unauth
    # Home address
    indexUrl: /index
    # Verification code switch
    captchaEnabled: false
    # Verification code type math array calculation char characters
    captchaType: math
  cookie:
    # Set the cookie domain name. The default is empty, which is the domain name currently visited
    domain: 
    # Set the effective access path of the cookie
    path: /
    # Set HttpOnly attribute
    httpOnly: true
    # Set the expiration time of the cookie, in days
    maxAge: 30
    # Set the key, be sure to maintain uniqueness (generate method, just copy to main to run) KeyGenerator keygen = KeyGenerator.getInstance("AES"); SecretKey deskey = keygen.generateKey(); System.out.println(Base64.encodeToString) (deskey.getEncoded()));
    cipherKey: zSyK5Kp6PZAAjlT+eeNMlg==
  session:
    # Session timeout, -1 means never expire (default 30 minutes)
    expireTime: 30
    # Period for synchronizing session to database (default 1 minute)
    dbSyncPeriod: 1
    # How often to check the validity of the session, the default is 10 minutes
    validationInterval: 10
    # The maximum number of sessions for the same user, for example, 2 means that the same account allows up to two people to log in at the same time (default -1 does not limit)
    maxSession: -1
    # Kick out users who have logged in before/after login, by default the users who have logged in before are kicked out
    kickoutAfter: false

# Prevent XSS attacks
xss: 
  # Filter switch
  enabled: true
  # Exclude links (multiple separated by commas)
  excludes: /system/notice/*
  # Match link
  urlPatterns: /system/*,/monitor/*,/tool/*

# Swagger configuration
swagger:
  # Whether to open swagger
  enabled: true
